# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

selection_prox_cpp <- function(x, groups, weights, strength) {
    .Call(`_treeFA_selection_prox_cpp`, x, groups, weights, strength)
}

selection_penalty_cpp <- function(beta, groups, weights) {
    .Call(`_treeFA_selection_penalty_cpp`, beta, groups, weights)
}

selection_fit_cpp <- function(Y, X, groups, weights, lambda, tau, family, intercept, ridge_param, step_size, abs_tol, rel_tol, max_iter, init_z, keep_history) {
    .Call(`_treeFA_selection_fit_cpp`, Y, X, groups, weights, lambda, tau, family, intercept, ridge_param, step_size, abs_tol, rel_tol, max_iter, init_z, keep_history)
}

prox_tree_cpp <- function(eta, lambda, tree_list) {
    .Call(`_treeFA_prox_tree_cpp`, eta, lambda, tree_list)
}

acc_prox_simple_linear_cpp <- function(Y, X, tree_result, lambda, init_beta, ridge_param, thresh, max_iter, stop_rule) {
    .Call(`_treeFA_acc_prox_simple_linear_cpp`, Y, X, tree_result, lambda, init_beta, ridge_param, thresh, max_iter, stop_rule)
}

