// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// selection_prox_cpp
Rcpp::NumericVector selection_prox_cpp(Rcpp::NumericVector x, Rcpp::List groups, Rcpp::NumericVector weights, double strength);
RcppExport SEXP _treeFA_selection_prox_cpp(SEXP xSEXP, SEXP groupsSEXP, SEXP weightsSEXP, SEXP strengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type strength(strengthSEXP);
    rcpp_result_gen = Rcpp::wrap(selection_prox_cpp(x, groups, weights, strength));
    return rcpp_result_gen;
END_RCPP
}
// selection_penalty_cpp
double selection_penalty_cpp(Rcpp::NumericVector beta, Rcpp::List groups, Rcpp::NumericVector weights);
RcppExport SEXP _treeFA_selection_penalty_cpp(SEXP betaSEXP, SEXP groupsSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(selection_penalty_cpp(beta, groups, weights));
    return rcpp_result_gen;
END_RCPP
}
// selection_fit_cpp
Rcpp::List selection_fit_cpp(Rcpp::NumericVector Y, Rcpp::NumericMatrix X, Rcpp::List groups, Rcpp::NumericVector weights, double lambda, double tau, int family, bool intercept, double ridge_param, double step_size, double abs_tol, double rel_tol, int max_iter, Rcpp::NumericVector init_z, bool keep_history);
RcppExport SEXP _treeFA_selection_fit_cpp(SEXP YSEXP, SEXP XSEXP, SEXP groupsSEXP, SEXP weightsSEXP, SEXP lambdaSEXP, SEXP tauSEXP, SEXP familySEXP, SEXP interceptSEXP, SEXP ridge_paramSEXP, SEXP step_sizeSEXP, SEXP abs_tolSEXP, SEXP rel_tolSEXP, SEXP max_iterSEXP, SEXP init_zSEXP, SEXP keep_historySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type family(familySEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< double >::type ridge_param(ridge_paramSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type abs_tol(abs_tolSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type init_z(init_zSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_history(keep_historySEXP);
    rcpp_result_gen = Rcpp::wrap(selection_fit_cpp(Y, X, groups, weights, lambda, tau, family, intercept, ridge_param, step_size, abs_tol, rel_tol, max_iter, init_z, keep_history));
    return rcpp_result_gen;
END_RCPP
}
// prox_tree_cpp
NumericVector prox_tree_cpp(NumericVector eta, double lambda, List tree_list);
RcppExport SEXP _treeFA_prox_tree_cpp(SEXP etaSEXP, SEXP lambdaSEXP, SEXP tree_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< List >::type tree_list(tree_listSEXP);
    rcpp_result_gen = Rcpp::wrap(prox_tree_cpp(eta, lambda, tree_list));
    return rcpp_result_gen;
END_RCPP
}
// acc_prox_simple_linear_cpp
List acc_prox_simple_linear_cpp(NumericVector Y, NumericMatrix X, List tree_result, double lambda, NumericVector init_beta, double ridge_param, double thresh, int max_iter, int stop_rule);
RcppExport SEXP _treeFA_acc_prox_simple_linear_cpp(SEXP YSEXP, SEXP XSEXP, SEXP tree_resultSEXP, SEXP lambdaSEXP, SEXP init_betaSEXP, SEXP ridge_paramSEXP, SEXP threshSEXP, SEXP max_iterSEXP, SEXP stop_ruleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type tree_result(tree_resultSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init_beta(init_betaSEXP);
    Rcpp::traits::input_parameter< double >::type ridge_param(ridge_paramSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type stop_rule(stop_ruleSEXP);
    rcpp_result_gen = Rcpp::wrap(acc_prox_simple_linear_cpp(Y, X, tree_result, lambda, init_beta, ridge_param, thresh, max_iter, stop_rule));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_treeFA_selection_prox_cpp", (DL_FUNC) &_treeFA_selection_prox_cpp, 4},
    {"_treeFA_selection_penalty_cpp", (DL_FUNC) &_treeFA_selection_penalty_cpp, 3},
    {"_treeFA_selection_fit_cpp", (DL_FUNC) &_treeFA_selection_fit_cpp, 15},
    {"_treeFA_prox_tree_cpp", (DL_FUNC) &_treeFA_prox_tree_cpp, 3},
    {"_treeFA_acc_prox_simple_linear_cpp", (DL_FUNC) &_treeFA_acc_prox_simple_linear_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_treeFA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
